import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import pokemonBackground from './../../public/grid.png'
import React, {useState, useEffect } from 'react'
import { supabase } from '../../api'
const inter = Inter({ subsets: ['latin'] })

function changeGIF(pokemon) {
  console.log(pokemon);
  var img = document.getElementById("test");
  img.src = "https://projectpokemon.org/images/normal-sprite/" + pokemon + ".gif";
}

function Home({ Kanto }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main class="mainPage">
        <div class="pokemonChoice">
        <ul>
      {Kanto.map((country) => (
        <li class="filler" onClick={() => changeGIF(country.Name)} key={country.id}>
          <Image width='70'height='70'src={'https://img.pokemondb.net/sprites/x-y/normal/' + country.Name + '.png'} alt='Bulbasaur'/>
          {country.Name}
          </li>
      ))}
    </ul>
        </div>
        <div class="pokemonGIF">
          <Image class="GIFBackground" src={pokemonBackground}/>
          <Image id="test" class="displayGIF" width='inherit'height='500'src=""/>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  let { data } = await supabase.from('Kanto').select()

  return {
    props: {
     Kanto: data
    },
  }
}

export default Home;